Alias /requerimentos /home/tars/requisicoes_ifsc_gpb/public

<Directory /home/tars/requisicoes_ifsc_gpb/public>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
